name: Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Build Pipeline
        working-directory: osgi-workshop
        run: |
          python build_pipeline.py changed

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: northwind-artifacts
          path: |
            **/target/*.jar
